name: flutter_showcase
description: Algolia Flutter Helpers showcase

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  algolia_helper_flutter: ^0.2.0
  widgetbook_annotation: ^2.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  widgetbook: ^2.4.1
  build_runner: ^2.3.0
  widgetbook_generator: ^2.4.1

flutter:
  uses-material-design: true
  fonts:
    - family: Hind
      fonts:
        - asset: fonts/Hind-Light.ttf
          weight: 300
        - asset: fonts/Hind-Regular.ttf
          weight: 400
        - asset: fonts/Hind-Medium.ttf
          weight: 500
        - asset: fonts/Hind-SemiBold.ttf
          weight: 600
        - asset: fonts/Hind-Bold.ttf
          weight: 700

